version: "3.1" 
services: 
  www:
    container_name: www_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app/public:/var/www/html
      - ./app:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:vNWHSHdpGSQ4ylaG81ONT/YKqLpi8EpHm/2Ri8148ac=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_DATABASE=bdsipe_dev 
      - DB_USERNAME=root 
      - DB_PASSWORD=sejus2020
    restart: always
    networks:
      - laravel_network
  db:
    container_name: mysql_container
    image: mysql:8.0
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=sejus2020
      - MYSQL_DATABASE=bdsipe_dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=master
    volumes: 
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin_container
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions
    links:
      - db
    networks:
      - laravel_network
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_container
    #restart: always
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge